// Automatically generated by build.bat 
// vim: shiftwidth=4 
// vim: ts=4 

package com.errapartengineering.LampController; 
import java.util.Date;

// Build info. 
public final class BuildInfo { 
	// Build date: Sun Nov 11 17:50:14 EET 2007
	public final static String buildDate = "2007-11-11 17:50:14";
	// Output log to serial?
	public final static boolean	logToSerial = false;
	// Capability to shutdown
	public final static boolean	shutDown = true;
	// Connected to the power light
	public final static boolean	powerLight = false;
	// Server IP:port
	public final static String server = "194.204.26.104:8080";
	public final static String compilationArguments = "-logToSerial,+shutDown,-powerLight,server=194.204.26.104:8080";
} // class Build 
