// Automatically generated by build.bat 
// vim: shiftwidth=4 
// vim: ts=4 

package com.errapartengineering.LampController; 
import java.util.Date;

// Build info. 
public final class BuildInfo { 
	// Build date: Sat Nov 24 21:22:25 EET 2007
	public final static String buildDate = "2007-11-24 21:22:25";
	// Output log to serial?
	public final static boolean	logToSerial = false;
	// Capability to shutdown
	public final static boolean	shutDown = false;
	// Connected to the power light
	public final static boolean	powerLight = true;
	// Server IP:port
	public final static String server = "194.204.26.104:8888";
	public final static String compilationArguments = "-logToSerial,-shutDown,+powerLight,server=194.204.26.104:8080";
} // class Build 
